In [5]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame
import numpy as np
import pandas as pd 
def create_dataframe():
    scores = np.random.randint(50,101,size=(50, 5))
    columns = ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
    index = ['學生' + str(i) for i in range(1, 51)]
    df = pd.DataFrame(scores, columns=columns[:-3], index=index)
    df['總分'] = df.sum(axis=1)
    df['平均'] = df.mean(axis=1)
    df['排名'] = df['總分'].rank(ascending=False)
    return df

In [7]:
df = create_dataframe()
df

       國文  英文  數學   自然  社會   總分          平均    排名
學生1    71  54  52   62  71  310  103.333333  49.0
學生2    52  58  55  100  59  324  108.000000  45.0
學生3    93  72  50   59  99  373  124.333333  17.0
學生4    61  98  95   96  57  407  135.666667   7.0
學生5    96  73  89   87  93  438  146.000000   3.0
學生6    87  57  88   51  70  353  117.666667  30.5
學生7    84  52  91   77  69  373  124.333333  17.0
學生8    92  73  72   80  66  383  127.666667  12.5
學生9    73  70  78   62  55  338  112.666667  40.0
學生10   70  81  66   81  70  368  122.666667  20.5
學生11   85  77  70   96  63  391  130.333333   9.0
學生12   73  57  84   97  62  373  124.333333  17.0
學生13   64  59  93   53  66  335  111.666667  41.0
學生14   94  77  78   95  60  404  134.666667   8.0
學生15   67  82  50   95  74  368  122.666667  20.5
學生16   79  93  96   99  89  456  152.000000   1.0
學生17   60  62  68   77  63  330  110.000000  42.5
學生18   67  59  99   60  64  349  116.333333  34.0
學生19   86  59  58   83  65  351  117.000000  32.0
學生20   59  87  77   79  59  361  120.333333  25.5
學生21   90  59  82   55  87  373  124.333333  17.0
學生22   81  63  73   62  67  346  115.333333  38.0
學生23   50  87  60   84  72  353  117.666667  30.5
學生24   56  53  83   69  54  315  105.000000  47.0
學生25  100  97  99   52  97  445  148.333333   2.0
學生26   87  98  58   56  61  360  120.000000  27.0
學生27   62  66  87   79  86  380  126.666667  14.0
學生28   97  57  62   64  68  348  116.000000  35.0
學生29   54  68  56   51  97  326  108.666667  44.0
學生30   94  92  62   57  68  373  124.333333  17.0
學生31   63  79  66   63  52  323  107.666667  46.0
學生32   50  52  82   84  79  347  115.666667  36.5
學生33   58  53  58   58  66  293   97.666667  50.0
學生34   72  92  80   85  88  417  139.000000   6.0
學生35   80  65  80   92  69  386  128.666667  10.0
學生36   57  90  91   71  58  367  122.333333  22.0
學生37   97  96  66   95  83  437  145.666667   4.0
學生38   56  56  77   97  99  385  128.333333  11.0
學生39   58  87  52   60  54  311  103.666667  48.0
學生40   89  56  56   79  50  330  110.000000  42.5
學生41   59  75  63   62  91  350  116.666667  33.0
學生42   51  81  54   79  90  355  118.333333  29.0
學生43   70  99  61   57  96  383  127.666667  12.5
學生44   66  98  93   75  89  421  140.333333   5.0
學生45   88  68  51   83  54  344  114.666667  39.0
學生46   55  92  53   50  97  347  115.666667  36.5
學生47   74  90  65   78  55  362  120.666667  24.0
學生48   50  73  97   76  70  366  122.000000  23.0
學生49   72  52  90   74  73  361  120.333333  25.5
學生50   64  67  73   80  73  357  119.000000  28.0

In [8]:
#建立1個統計的DataFrame
def create_statistics_dataframe(df):
    cols = ['國文', '英文', '數學', '自然', '社會']
    stats = df[cols].agg(['mean', 'max', 'min', 'median'])
    stats.index = ['平均', '最高', '最低', '中間值']
    return stats
create_statistics_dataframe(df)

         國文     英文     數學      自然     社會
平均    72.26  73.22  72.78   74.32  72.34
最高   100.00  99.00  99.00  100.00  99.00
最低    50.00  52.00  50.00   50.00  50.00
中間值   70.50  72.50  72.50   77.00  69.00