In [18]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(16).reshape(4,4),
                   index=['台北','台中', '台南', '高雄'],
                   columns=['one', 'two', 'three', 'four'])
df

    one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

In [19]:
#drop
df.drop(index=['台北', '高雄'], inplace=True)
df

    one  two  three  four
台中    4    5      6     7
台南    8    9     10    11

In [20]:
#排序和排名

scores = np.random.randint(50,101,size=(50, 5))
df = pd.DataFrame(scores,
                  columns=['國文', '英文', '數學', '自然', '社會'],
                  index=['學生' + str(i) for i in range(1, 51)])
df.index.name = '學生'
df.columns.name = '科目'
sum_values = df.sum(axis=1)
mean_values = df.mean(axis=1)
df['總分'] = sum_values
df['平均'] = mean_values
df

科目    國文   英文   數學  自然   社會   總分    平均
學生
學生1   94   96   84  75   99  448  89.6
學生2   76   81   84  84   77  402  80.4
學生3   66   98   90  87   94  435  87.0
學生4   81  100   84  54   97  416  83.2
學生5   82   80   63  64   94  383  76.6
學生6   73   77   60  50   64  324  64.8
學生7   87   57   75  68   67  354  70.8
學生8   95   85   74  69  100  423  84.6
學生9   52   63   72  83   73  343  68.6
學生10  70   99   57  88   85  399  79.8
學生11  70   63   80  62   75  350  70.0
學生12  92   73   77  64   55  361  72.2
學生13  83   52   75  83   68  361  72.2
學生14  53   66   61  86   73  339  67.8
學生15  61   61   94  76   82  374  74.8
學生16  68   96   74  94   66  398  79.6
學生17  86   99  100  58   62  405  81.0
學生18  99   84   72  76   59  390  78.0
學生19  65   50   70  71   66  322  64.4
學生20  55   86   93  96   95  425  85.0
學生21  99   97   66  81   61  404  80.8
學生22  72   88   75  90   69  394  78.8
學生23  72   72   57  82   55  338  67.6
學生24  94   95   57  86   96  428  85.6
學生25  95   70   84  68   63  380  76.0
學生26  63   87   68  69   96  383  76.6
學生27  92   66   88  64   88  398  79.6
學生28  81   92   93  82   69  417  83.4
學生29  87   60   77  52   59  335  67.0
學生30  81   55   61  64   87  348  69.6
學生31  85   51   56  74   94  360  72.0
學生32  99   50   84  85   60  378  75.6
學生33  57   52   99  92   51  351  70.2
學生34  79   57   73  76   90  375  75.0
學生35  55   75   52  86   91  359  71.8
學生36  65   90   97  61   65  378  75.6
學生37  86   63   99  84   81  413  82.6
學生38  91   98   64  67   53  373  74.6
學生39  93   62   55  58   57  325  65.0
學生40  87   59   83  88   50  367  73.4
學生41  53   78   72  55   60  318  63.6
學生42  69   81   84  74   91  399  79.8
學生43  78   73   51  98   94  394  78.8
學生44  90   93   70  70   82  405  81.0
學生45  89   91   80  72   73  405  81.0
學生46  83   99   98  50   88  418  83.6
學生47  73   89   56  75   91  384  76.8
學生48  75   83   99  76   58  391  78.2
學生49  51   59   77  64   73  324  64.8
學生50  69   81   56  71   80  357  71.4

In [21]:
#排序和排名
#rank()
rank_values = sum_values.rank(method='min', ascending=False)
df['排名'] = rank_values
df

科目    國文   英文   數學  自然   社會   總分    平均    排名
學生
學生1   94   96   84  75   99  448  89.6   1.0
學生2   76   81   84  84   77  402  80.4  14.0
學生3   66   98   90  87   94  435  87.0   2.0
學生4   81  100   84  54   97  416  83.2   8.0
學生5   82   80   63  64   94  383  76.6  24.0
學生6   73   77   60  50   64  324  64.8  47.0
學生7   87   57   75  68   67  354  70.8  38.0
學生8   95   85   74  69  100  423  84.6   5.0
學生9   52   63   72  83   73  343  68.6  42.0
學生10  70   99   57  88   85  399  79.8  15.0
學生11  70   63   80  62   75  350  70.0  40.0
學生12  92   73   77  64   55  361  72.2  33.0
學生13  83   52   75  83   68  361  72.2  33.0
學生14  53   66   61  86   73  339  67.8  43.0
學生15  61   61   94  76   82  374  74.8  30.0
學生16  68   96   74  94   66  398  79.6  17.0
學生17  86   99  100  58   62  405  81.0  10.0
學生18  99   84   72  76   59  390  78.0  22.0
學生19  65   50   70  71   66  322  64.4  49.0
學生20  55   86   93  96   95  425  85.0   4.0
學生21  99   97   66  81   61  404  80.8  13.0
學生22  72   88   75  90   69  394  78.8  19.0
學生23  72   72   57  82   55  338  67.6  44.0
學生24  94   95   57  86   96  428  85.6   3.0
學生25  95   70   84  68   63  380  76.0  26.0
學生26  63   87   68  69   96  383  76.6  24.0
學生27  92   66   88  64   88  398  79.6  17.0
學生28  81   92   93  82   69  417  83.4   7.0
學生29  87   60   77  52   59  335  67.0  45.0
學生30  81   55   61  64   87  348  69.6  41.0
學生31  85   51   56  74   94  360  72.0  35.0
學生32  99   50   84  85   60  378  75.6  27.0
學生33  57   52   99  92   51  351  70.2  39.0
學生34  79   57   73  76   90  375  75.0  29.0
學生35  55   75   52  86   91  359  71.8  36.0
學生36  65   90   97  61   65  378  75.6  27.0
學生37  86   63   99  84   81  413  82.6   9.0
學生38  91   98   64  67   53  373  74.6  31.0
學生39  93   62   55  58   57  325  65.0  46.0
學生40  87   59   83  88   50  367  73.4  32.0
學生41  53   78   72  55   60  318  63.6  50.0
學生42  69   81   84  74   91  399  79.8  15.0
學生43  78   73   51  98   94  394  78.8  19.0
學生44  90   93   70  70   82  405  81.0  10.0
學生45  89   91   80  72   73  405  81.0  10.0
學生46  83   99   98  50   88  418  83.6   6.0
學生47  73   89   56  75   91  384  76.8  23.0
學生48  75   83   99  76   58  391  78.2  21.0
學生49  51   59   77  64   73  324  64.8  47.0
學生50  69   81   56  71   80  357  71.4  37.0

In [22]:
#sort_values()
#sort_index()
df1 = df.sort_values(by='總分', ascending=False)
df1

科目    國文   英文   數學  自然   社會   總分    平均    排名
學生
學生1   94   96   84  75   99  448  89.6   1.0
學生3   66   98   90  87   94  435  87.0   2.0
學生24  94   95   57  86   96  428  85.6   3.0
學生20  55   86   93  96   95  425  85.0   4.0
學生8   95   85   74  69  100  423  84.6   5.0
學生46  83   99   98  50   88  418  83.6   6.0
學生28  81   92   93  82   69  417  83.4   7.0
學生4   81  100   84  54   97  416  83.2   8.0
學生37  86   63   99  84   81  413  82.6   9.0
學生17  86   99  100  58   62  405  81.0  10.0
學生44  90   93   70  70   82  405  81.0  10.0
學生45  89   91   80  72   73  405  81.0  10.0
學生21  99   97   66  81   61  404  80.8  13.0
學生2   76   81   84  84   77  402  80.4  14.0
學生10  70   99   57  88   85  399  79.8  15.0
學生42  69   81   84  74   91  399  79.8  15.0
學生27  92   66   88  64   88  398  79.6  17.0
學生16  68   96   74  94   66  398  79.6  17.0
學生43  78   73   51  98   94  394  78.8  19.0
學生22  72   88   75  90   69  394  78.8  19.0
學生48  75   83   99  76   58  391  78.2  21.0
學生18  99   84   72  76   59  390  78.0  22.0
學生47  73   89   56  75   91  384  76.8  23.0
學生5   82   80   63  64   94  383  76.6  24.0
學生26  63   87   68  69   96  383  76.6  24.0
學生25  95   70   84  68   63  380  76.0  26.0
學生36  65   90   97  61   65  378  75.6  27.0
學生32  99   50   84  85   60  378  75.6  27.0
學生34  79   57   73  76   90  375  75.0  29.0
學生15  61   61   94  76   82  374  74.8  30.0
學生38  91   98   64  67   53  373  74.6  31.0
學生40  87   59   83  88   50  367  73.4  32.0
學生13  83   52   75  83   68  361  72.2  33.0
學生12  92   73   77  64   55  361  72.2  33.0
學生31  85   51   56  74   94  360  72.0  35.0
學生35  55   75   52  86   91  359  71.8  36.0
學生50  69   81   56  71   80  357  71.4  37.0
學生7   87   57   75  68   67  354  70.8  38.0
學生33  57   52   99  92   51  351  70.2  39.0
學生11  70   63   80  62   75  350  70.0  40.0
學生30  81   55   61  64   87  348  69.6  41.0
學生9   52   63   72  83   73  343  68.6  42.0
學生14  53   66   61  86   73  339  67.8  43.0
學生23  72   72   57  82   55  338  67.6  44.0
學生29  87   60   77  52   59  335  67.0  45.0
學生39  93   62   55  58   57  325  65.0  46.0
學生6   73   77   60  50   64  324  64.8  47.0
學生49  51   59   77  64   73  324  64.8  47.0
學生19  65   50   70  71   66  322  64.4  49.0
學生41  53   78   72  55   60  318  63.6  50.0