In [7]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame
import numpy as np
import pandas as pd 

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df

scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df

科目    國文  英文   數學   自然   社會   總分    平均    排名
學生
學生1   98  51   50   74   83  356  71.2  39.0
學生2   74  94   71   99   68  406  81.2  14.0
學生3   97  87   79   88   56  407  81.4  10.0
學生4   68  97   82   83   89  419  83.8   5.0
學生5   68  76   65  100   57  366  73.2  32.0
學生6   91  63   74   79   92  399  79.8  16.0
學生7   66  87   72   91   78  394  78.8  19.0
學生8   70  90   81   65   71  377  75.4  29.0
學生9   95  97   83   60   62  397  79.4  18.0
學生10  81  98   52   81   98  410  82.0   8.0
學生11  74  87   67   51   65  344  68.8  46.0
學生12  53  75   86   98   94  406  81.2  14.0
學生13  88  60   69   80   91  388  77.6  23.0
學生14  56  82   69   91   87  385  77.0  25.0
學生15  89  67   59   60   73  348  69.6  44.0
學生16  88  58   94   59  100  399  79.8  16.0
學生17  68  95   55   58   73  349  69.8  41.0
學生18  72  68   95   68   62  365  73.0  33.0
學生19  68  90   94   66   89  407  81.4  10.0
學生20  95  95   87   81   86  444  88.8   4.0
學生21  95  93   65   54  100  407  81.4  10.0
學生22  50  62   53   65   72  302  60.4  50.0
學生23  84  74   56   50   86  350  70.0  40.0
學生24  97  88   95   78   97  455  91.0   1.0
學生25  82  94   59   67   56  358  71.6  37.0
學生26  90  79   87   81   82  419  83.8   5.0
學生27  62  93   67   68   91  381  76.2  26.0
學生28  61  95   96   54   72  378  75.6  28.0
學生29  54  95   52   62   81  344  68.8  46.0
學生30  79  56   78   69   99  381  76.2  26.0
學生31  98  78   64   63   73  376  75.2  30.0
學生32  87  88   53   89   90  407  81.4  10.0
學生33  83  54   90   99   67  393  78.6  20.0
學生34  59  62   68   94   74  357  71.4  38.0
學生35  51  66   50   60   95  322  64.4  48.0
學生36  95  83  100   71   99  448  89.6   2.0
學生37  76  87   71  100   77  411  82.2   7.0
學生38  59  88   74   99   90  410  82.0   8.0
學生39  54  98   60   59   78  349  69.8  41.0
學生40  93  73   91   68   68  393  78.6  20.0
學生41  77  50   81   62   79  349  69.8  41.0
學生42  73  52   74   60   88  347  69.4  45.0
學生43  72  51   88   82   96  389  77.8  22.0
學生44  61  52   56   68   71  308  61.6  49.0
學生45  89  97   97   86   76  445  89.0   3.0
學生46  86  83   52   80   71  372  74.4  31.0
學生47  93  60   63   86   86  388  77.6  23.0
學生48  58  65   55   83   98  359  71.8  36.0
學生49  94  81   68   59   63  365  73.0  33.0
學生50  76  53   65  100   71  365  73.0  33.0

In [8]:
#選擇欄位
df1 = df[['國文', '英文', '數學', '自然', '社會']]
df1

科目    國文  英文   數學   自然   社會
學生
學生1   98  51   50   74   83
學生2   74  94   71   99   68
學生3   97  87   79   88   56
學生4   68  97   82   83   89
學生5   68  76   65  100   57
學生6   91  63   74   79   92
學生7   66  87   72   91   78
學生8   70  90   81   65   71
學生9   95  97   83   60   62
學生10  81  98   52   81   98
學生11  74  87   67   51   65
學生12  53  75   86   98   94
學生13  88  60   69   80   91
學生14  56  82   69   91   87
學生15  89  67   59   60   73
學生16  88  58   94   59  100
學生17  68  95   55   58   73
學生18  72  68   95   68   62
學生19  68  90   94   66   89
學生20  95  95   87   81   86
學生21  95  93   65   54  100
學生22  50  62   53   65   72
學生23  84  74   56   50   86
學生24  97  88   95   78   97
學生25  82  94   59   67   56
學生26  90  79   87   81   82
學生27  62  93   67   68   91
學生28  61  95   96   54   72
學生29  54  95   52   62   81
學生30  79  56   78   69   99
學生31  98  78   64   63   73
學生32  87  88   53   89   90
學生33  83  54   90   99   67
學生34  59  62   68   94   74
學生35  51  66   50   60   95
學生36  95  83  100   71   99
學生37  76  87   71  100   77
學生38  59  88   74   99   90
學生39  54  98   60   59   78
學生40  93  73   91   68   68
學生41  77  50   81   62   79
學生42  73  52   74   60   88
學生43  72  51   88   82   96
學生44  61  52   56   68   71
學生45  89  97   97   86   76
學生46  86  83   52   80   71
學生47  93  60   63   86   86
學生48  58  65   55   83   98
學生49  94  81   68   59   63
學生50  76  53   65  100   71

In [9]:
s = df1.loc['學生1']
less_than_60_series = s[s<60]
#取出不及格的科目
failing_subjects = less_than_60_series.index.tolist()
failing_subjects
#取出不及格科目的分數
failing_scores = less_than_60_series.tolist()
failing_scores
#建立一個Series,值要轉換為字串,如果有多個值則用逗號分隔
failing_scores_str = ','.join(map(str, failing_scores))
failing_subjects_str = ','.join(failing_subjects)
pd.Series([failing_scores_str, failing_subjects_str], index=['分數', '不及格科目'])

分數       51,50
不及格科目    英文,數學
dtype: object

In [10]:
def apply_statistics(s):
    less_than_60_series = s[s<60]
    #不及格科目數量
    failing_subjects_count = less_than_60_series.count()
    #取出不及格的科目
    failing_subjects = less_than_60_series.index.tolist()
    
    #取出不及格科目的分數
    failing_scores = less_than_60_series.tolist()
    
    #建立一個Series,值要轉換為字串,如果有多個值則用逗號分隔
    failing_scores_str = ','.join(map(str, failing_scores))
    failing_subjects_str = ','.join(failing_subjects)
    return pd.Series([failing_subjects_count,failing_subjects_str,failing_scores_str], index=['不及格科目數量', '不及格科目', '分數'])


df2 = df1.apply(apply_statistics, axis=1)
df2

      不及格科目數量  不及格科目     分數
學生
學生1         2  英文,數學  51,50
學生2         0
學生3         1     社會     56
學生4         0
學生5         1     社會     57
學生6         0
學生7         0
學生8         0
學生9         0
學生10        1     數學     52
學生11        1     自然     51
學生12        1     國文     53
學生13        0
學生14        1     國文     56
學生15        1     數學     59
學生16        2  英文,自然  58,59
學生17        2  數學,自然  55,58
學生18        0
學生19        0
學生20        0
學生21        1     自然     54
學生22        2  國文,數學  50,53
學生23        2  數學,自然  56,50
學生24        0
學生25        2  數學,社會  59,56
學生26        0
學生27        0
學生28        1     自然     54
學生29        2  國文,數學  54,52
學生30        1     英文     56
學生31        0
學生32        1     數學     53
學生33        1     英文     54
學生34        1     國文     59
學生35        2  國文,數學  51,50
學生36        0
學生37        0
學生38        1     國文     59
學生39        2  國文,自然  54,59
學生40        0
學生41        1     英文     50
學生42        1     英文     52
學生43        1     英文     51
學生44        2  英文,數學  52,56
學生45        0
學生46        1     數學     52
學生47        0
學生48        2  國文,數學  58,55
學生49        1     自然     59
學生50        1     英文     53

In [12]:
#df和df2合併
df3 = pd.concat([df, df2], axis=1)
df3

      國文  英文   數學   自然   社會   總分    平均    排名  不及格科目數量  不及格科目     分數
學生
學生1   98  51   50   74   83  356  71.2  39.0        2  英文,數學  51,50
學生2   74  94   71   99   68  406  81.2  14.0        0
學生3   97  87   79   88   56  407  81.4  10.0        1     社會     56
學生4   68  97   82   83   89  419  83.8   5.0        0
學生5   68  76   65  100   57  366  73.2  32.0        1     社會     57
學生6   91  63   74   79   92  399  79.8  16.0        0
學生7   66  87   72   91   78  394  78.8  19.0        0
學生8   70  90   81   65   71  377  75.4  29.0        0
學生9   95  97   83   60   62  397  79.4  18.0        0
學生10  81  98   52   81   98  410  82.0   8.0        1     數學     52
學生11  74  87   67   51   65  344  68.8  46.0        1     自然     51
學生12  53  75   86   98   94  406  81.2  14.0        1     國文     53
學生13  88  60   69   80   91  388  77.6  23.0        0
學生14  56  82   69   91   87  385  77.0  25.0        1     國文     56
學生15  89  67   59   60   73  348  69.6  44.0        1     數學     59
學生16  88  58   94   59  100  399  79.8  16.0        2  英文,自然  58,59
學生17  68  95   55   58   73  349  69.8  41.0        2  數學,自然  55,58
學生18  72  68   95   68   62  365  73.0  33.0        0
學生19  68  90   94   66   89  407  81.4  10.0        0
學生20  95  95   87   81   86  444  88.8   4.0        0
學生21  95  93   65   54  100  407  81.4  10.0        1     自然     54
學生22  50  62   53   65   72  302  60.4  50.0        2  國文,數學  50,53
學生23  84  74   56   50   86  350  70.0  40.0        2  數學,自然  56,50
學生24  97  88   95   78   97  455  91.0   1.0        0
學生25  82  94   59   67   56  358  71.6  37.0        2  數學,社會  59,56
學生26  90  79   87   81   82  419  83.8   5.0        0
學生27  62  93   67   68   91  381  76.2  26.0        0
學生28  61  95   96   54   72  378  75.6  28.0        1     自然     54
學生29  54  95   52   62   81  344  68.8  46.0        2  國文,數學  54,52
學生30  79  56   78   69   99  381  76.2  26.0        1     英文     56
學生31  98  78   64   63   73  376  75.2  30.0        0
學生32  87  88   53   89   90  407  81.4  10.0        1     數學     53
學生33  83  54   90   99   67  393  78.6  20.0        1     英文     54
學生34  59  62   68   94   74  357  71.4  38.0        1     國文     59
學生35  51  66   50   60   95  322  64.4  48.0        2  國文,數學  51,50
學生36  95  83  100   71   99  448  89.6   2.0        0
學生37  76  87   71  100   77  411  82.2   7.0        0
學生38  59  88   74   99   90  410  82.0   8.0        1     國文     59
學生39  54  98   60   59   78  349  69.8  41.0        2  國文,自然  54,59
學生40  93  73   91   68   68  393  78.6  20.0        0
學生41  77  50   81   62   79  349  69.8  41.0        1     英文     50
學生42  73  52   74   60   88  347  69.4  45.0        1     英文     52
學生43  72  51   88   82   96  389  77.8  22.0        1     英文     51
學生44  61  52   56   68   71  308  61.6  49.0        2  英文,數學  52,56
學生45  89  97   97   86   76  445  89.0   3.0        0
學生46  86  83   52   80   71  372  74.4  31.0        1     數學     52
學生47  93  60   63   86   86  388  77.6  23.0        0
學生48  58  65   55   83   98  359  71.8  36.0        2  國文,數學  58,55
學生49  94  81   68   59   63  365  73.0  33.0        1     自然     59
學生50  76  53   65  100   71  365  73.0  33.0        1     英文     53

In [14]:
#df3請儲存為excel檔
df3.to_excel('df3.xlsx')